# Generated by Django 3.0.8 on 2021-05-14 16:14

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watching', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='listing',
            name='price',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='sold',
        ),
        migrations.AddField(
            model_name='listing',
            name='cook_time',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AddField(
            model_name='listing',
            name='ingredients',
            field=models.TextField(default='Ingredients not entered'),
        ),
        migrations.AddField(
            model_name='listing',
            name='prep_time',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AddField(
            model_name='listing',
            name='steps',
            field=models.TextField(default='Steps not entered'),
        ),
        migrations.DeleteModel(
            name='Bid',
        ),
        migrations.AddField(
            model_name='favourite',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.Listing'),
        ),
        migrations.AddField(
            model_name='favourite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
