# Generated by Django 3.0.8 on 2021-05-17 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20210514_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='steps',
            field=models.TextField(),
        ),
    ]
